FROM python:3.9-buster AS build

RUN apt-get update
RUN apt-get -y install librocksdb-dev libsnappy-dev liblz4-dev

RUN pip install poetry
RUN poetry config virtualenvs.create false

COPY . faust-demo
WORKDIR faust-demo
RUN poetry install

